application: furnaceathome
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /apple-touch-icon.png
  static_files: media/apple-touch-icon.png
  upload: media/apple-touch-icon.png

- url: /media
  static_dir: media

- url: /.*
  script: furnace.app
